/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfazUsuario;

import control.Control;
import java.awt.Container;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;

/**
 *
 * @author coond
 */
public class FrmEditor extends javax.swing.JFrame {
    private Container contenedor;
    JLabel labelTitulo;/*declaramos el objeto Label*/
    JTextArea areaDeTexto;
    JButton botonAbrir;/*declaramos el objeto Boton*/
    JButton botonGuardar;/*declaramos el objeto Boton*/
    JScrollPane scrollPaneArea;
    JFileChooser fileChooser; /*Declaramos el objeto fileChooser*/
    String texto;
    public FrmEditor() {
        initComponents();
        setSize(600, 450);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        opcionMenuNuevo = new javax.swing.JMenuItem();
        opcionMenuAbrir = new javax.swing.JMenuItem();
        opcionMenuGuardar = new javax.swing.JMenuItem();
        opcionMenuGuardarComo = new javax.swing.JMenuItem();
        opcionMenuEliminar = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        opcionMenuSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
        );

        jMenu1.setText("Archivos");

        opcionMenuNuevo.setText("Nuevo");
        opcionMenuNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionMenuNuevoActionPerformed(evt);
            }
        });
        jMenu1.add(opcionMenuNuevo);

        opcionMenuAbrir.setText("Abrir");
        opcionMenuAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionMenuAbrirActionPerformed(evt);
            }
        });
        jMenu1.add(opcionMenuAbrir);

        opcionMenuGuardar.setText("Guardar");
        jMenu1.add(opcionMenuGuardar);

        opcionMenuGuardarComo.setText("Guardar como");
        opcionMenuGuardarComo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionMenuGuardarComoActionPerformed(evt);
            }
        });
        jMenu1.add(opcionMenuGuardarComo);

        opcionMenuEliminar.setText("Eliminar");
        jMenu1.add(opcionMenuEliminar);
        jMenu1.add(jSeparator1);

        opcionMenuSalir.setText("Salir");
        jMenu1.add(opcionMenuSalir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edición");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Ayuda");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opcionMenuNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionMenuNuevoActionPerformed
        // TODO add your handling code here:
        Control control = new Control();
        if (control.nuevoArchivo(this)) {
           jTextArea2.setText("");  
        }
    }//GEN-LAST:event_opcionMenuNuevoActionPerformed

    private void opcionMenuGuardarComoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionMenuGuardarComoActionPerformed
       
    }//GEN-LAST:event_opcionMenuGuardarComoActionPerformed

    private void opcionMenuAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionMenuAbrirActionPerformed
        
    }//GEN-LAST:event_opcionMenuAbrirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold> 
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmEditor().setVisible(true);
                 
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JMenuItem opcionMenuAbrir;
    private javax.swing.JMenuItem opcionMenuEliminar;
    private javax.swing.JMenuItem opcionMenuGuardar;
    private javax.swing.JMenuItem opcionMenuGuardarComo;
    private javax.swing.JMenuItem opcionMenuNuevo;
    private javax.swing.JMenuItem opcionMenuSalir;
    // End of variables declaration//GEN-END:variables
}
